local lazypath = vim.fn.stdpath("data") .. "/lazy/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
	vim.fn.system({
		"git",
		"clone",
		"--filter=blob:none",
		"https://github.com/folke/lazy.nvim.git",
		"--branch=stable", -- latest stable release
		lazypath,
	})
end
vim.opt.rtp:prepend(lazypath)

require('lazy').setup({
	require('config.plugins.ui.colorscheme'),
	require('config.plugins.utils.telescope').config,
	require('config.plugins.editor.yank'),
	require('config.plugins.editor.debugger'),
	require('config.plugins.editor.flutter'),
	require('config.plugins.editor.ft'),
	require('config.plugins.editor.indent'),
	require('config.plugins.ui.winbar'),
	require('config.plugins.utils.treesitter'),
	require('config.plugins.ui.tabbar'),
	require('config.plugins.editor.editor'),
	require('config.plugins.ui.scrollbar'),
	require('config.plugins.editor.git'),
	require('config.plugins.extra.fun'),
	require('config.plugins.editor.surround'),
	require('config.plugins.editor.lspconfig').config,
	require('config.plugins.utils.mason'),
	require('config.plugins.utils.autocomplete').config,
	require('config.plugins.ui.notify'),
	require('config.plugins.utils.fzf'),
	require('config.plugins.ui.statusbar'),
	require('config.plugins.editor.snippets'),
	require('config.plugins.editor.search'),
	require('config.plugins.editor.comment'),
	require('config.plugins.utils.project'),
	require('config.plugins.utils.window-manager'),
	require('config.plugins.editor.undo'),
	require('config.plugins.ui.wilder'),
	require('config.plugins.editor.tex'),
	require('config.plugins.editor.markdown'),
	require('config.plugins.ui.joshuto'),
	require('config.plugins.ui.toggleterm'),
	require('config.plugins.ui.neo-tree'),
	require('config.plugins.utils.virtual-env'),
	require('config.plugins.editor.copilot'),
})
